---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meetbot-config
  namespace: meeting
data:
  nick: mindspore-ci-bot
  ident: mindspore-ci-bot
  username: mindspore-ci-bot
  irc_channels: "#mindspore-discuss #mindspore-sc"
  url_info: https://mindspore.cn/
  log_url_prefix: http://meeting.mindspore.cn/
  log_pattern: "%(channel)s/%%Y/%(meetingname)s/%%F-%%H.%%M"
  nginx.conf: |
    user  root;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        keepalive_timeout  65;
        server {
            listen 8080;                 ##listen port
            server_name meeting.mindspore.cn;   ##server_name domain
            location / {
                root /usr/share/nginx/html/public_html;  ## work folder
                autoindex on;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }  
    
